export const CREATE_TEAM_MEMBER_LOAD = 'createTeamMember/CREATE_TEAM_MEMBER_LOAD';
export const CREATE_TEAM_MEMBER_SUCCESS = 'createTeamMember/CREATE_TEAM_MEMBER_SUCCESS';
export const CREATE_TEAM_MEMBER_FAILURE = 'createTeamMember/CREATE_TEAM_MEMBER_FAIL';

export const CREATE_TEAM_HEAD_LOAD = 'createTeamHead/CREATE_TEAM_HEAD_LOAD';
export const CREATE_TEAM_HEAD_SUCCESS = 'createTeamHead/CREATE_TEAM_HEAD_SUCCESS';
export const CREATE_TEAM_HEAD_FAILURE = 'createTeamHead/CREATE_TEAM_HEAD_FAILURE';

export const GET_TEAM_MEMBERS_LOAD = 'getTeamMembers/GET_TEAM_MEMBERS_LOAD';
export const GET_TEAM_MEMBERS_SUCCESS = 'getTeamMembers/GET_TEAM_MEMBERS_SUCCESS';
export const GET_TEAM_MEMBERS_FAILURE = 'getTeamMembers/GET_TEAM_MEMBERS_FAILURE';

export const EDIT_TEAM_MEMBER_LOAD = 'editTeamMember/EDIT_TEAM_MEMBER_LOAD';
export const EDIT_TEAM_MEMBER_SUCCESS = 'editTeamMember/EDIT_TEAM_MEMBER_SUCCESS';
export const EDIT_TEAM_MEMBER_FAILURE = 'editTeamMember/EDIT_TEAM_MEMBER_FAILURE';

export const SEND_CRENDENTIAL_LOAD = 'sendCredential/SEND_CRENDENTIAL_LOAD';
export const SEND_CRENDENTIAL_SUCCESS = 'sendCredential/SEND_CRENDENTIAL_SUCCESS';
export const SEND_CRENDENTIAL_FAILURE = 'sendCredential/SEND_CRENDENTIAL_FAILURE';

export const RESEND_CRENDENTIAL_LOAD = 'resendCredential/RESEND_CRENDENTIAL_LOAD';
export const RESEND_CRENDENTIAL_SUCCESS = 'resendCredential/RESEND_CRENDENTIAL_SUCCESS';
export const RESEND_CRENDENTIAL_FAILURE = 'resendCredential/RESEND_CRENDENTIAL_FAILURE';

export const DIRECT_REPORTING_LOAD = 'directReporting/DIRECT_REPORTING_LOAD';
export const DIRECT_REPORTING_SUCCESS = 'directReporting/DIRECT_REPORTING_SUCCESS';
export const DIRECT_REPORTING_FAILURE = 'directReporting/DIRECT_REPORTING_FAILURE';

export const DELETE_TEAM_MEMBER_LOAD = 'deleteTeamMember/DELETE_TEAM_MEMBER_LOAD';
export const DELETE_TEAM_MEMBER_SUCCESS = 'deleteTeamMember/DELETE_TEAM_MEMBER_SUCCESS';
export const DELETE_TEAM_MEMBER_FAILURE = 'deleteTeamMember/DELETE_TEAM_MEMBER_FAILURE';

