export const LEAD_MONTHLY_SUMMARY_LOAD = 'inventoryInfo/LEAD_MONTHLY_SUMMARY_LOAD';
export const LEAD_MONTHLY_SUMMARY_SUCCESS = 'inventoryInfo/LEAD_MONTHLY_SUMMARY_SUCCESS';
export const LEAD_MONTHLY_SUMMARY_FAIL = 'inventoryInfo/LEAD_MONTHLY_SUMMARY_FAIL';
